# Generated by Django 4.2.4 on 2023-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField()),
                ('lng', models.IntegerField()),
                ('name', models.CharField(max_length=120, null=True)),
                ('description', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
