# Generated by Django 4.2.4 on 2023-08-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lng',
            field=models.FloatField(),
        ),
    ]
